# Cerberus Copyright (C) 2016 Cerberus Testing
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This file is part of Cerberus.
#
# Cerberus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cerberus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cerberus. If not, see <http://www.gnu.org/licenses/>.
# Cerberus Glassfish MySQL composition.

version: '3'
services:
  database:
    image: cerberustesting/cerberus-db-mysql:latest
    expose:
      - "3306"
    ports:
      - "13306:3306"
    volumes:
      - ./localdata/mysql-db:/var/lib/mysql
#      - /etc/localtime:/etc/localtime:ro
    restart: always
  cerberus-as-tomcat-keycloak:
    image: cerberustesting/cerberus-as-tomcat-keycloak:latest
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - KEYCLOAK_URL=http://192.168.1.70:38080/auth
      - KEYCLOAK_REALM=Cerberus
      - KEYCLOAK_CLIENT=cerberus
    ports:
      - "8080:8080"
    volumes:
      - ./localdata/cerberusmedia:/opt/CerberusMedias/
#      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - database
    links:
      - database
  # Selenium-related services
  selenium-hub:
    image: selenium/hub:3.141.59
    expose:
      - "4444"
    ports:
      - "14444:4444"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    restart: always
  selenium-node-firefox:
    image: selenium/node-firefox-debug:3.141.59-zirconium
    environment:
      HUB_HOST: selenium-hub
    expose:
      - "5900"
    depends_on:
      - selenium-hub
    ports:
      - "15900:5900"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    restart: always
  selenium-node-chrome:
    image: selenium/node-chrome-debug:3.141.59-zirconium
    environment:
      HUB_HOST: selenium-hub
    expose:
      - "5900"
    depends_on:
      - selenium-hub
    ports:
      - "15901:5900"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    restart: always
